apiVersion: v1
kind: ServiceAccount
metadata:
  name: poorbricks-server
  namespace: poorbricks
  annotations:
    iam.gke.io/gcp-service-account: poorbricks-server@inner-autonomy-371516.iam.gserviceaccount.com
