apiVersion: v1
kind: Namespace
metadata:
  name: poorbricks
  labels:
    app.kubernetes.io/name: poorbricks
---
apiVersion: v1
kind: Namespace
metadata:
  name: poorbricks-workers
  labels:
    app.kubernetes.io/name: poorbricks-workers
