apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker
spec:
  serviceAccountName: airflow
  nodeSelector:
    cloud.google.com/gke-nodepool: spot
  tolerations:
  - key: spot
    operator: Equal
    value: "true"
    effect: NoSchedule
  containers:
    - name: base
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
          readOnly: true
  volumes:
    - name: dags
      persistentVolumeClaim:
        claimName: airflow-dags
        readOnly: true
