apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  template:
    spec:
      volumes:
        - name: dags
          emptyDir: {}
      containers:
        # Add sidecar container
        - name: gcs-sync
          image: google/cloud-sdk:slim
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              while true; do
                gsutil -m rsync -d -r gs://poorbricks-airflow-dags /opt/airflow/dags || true
                sleep 30
              done
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
