"""Cross-machine deterministic snapshots, committed to git.

Each pipeline keeps a JSON snapshot at ``tests/snapshots/<pipeline_key>.json``
that captures: schema, full row count, a SHA-256 hash of every row in
canonical sort order, and a sample of the first N rows for human-readable
diffs. The format is committed; the regression check
(``make check-snapshot``) hashes the current output the same way and
compares.

This replaces the old per-developer Parquet snapshots that lived in the
gitignored ``tests/snapshots/`` directory. The JSON format trades a few
KB for portability — Parquet bytes are nondeterministic across machines
(float ordering, struct key ordering, etc.) and could not be committed.

Public API:
    write_snapshot(df, pipeline_key, source, sort_keys=None)
        Overwrite the committed snapshot.
    diff_against_snapshot(df, pipeline_key)
        Return a list of human-readable drift lines; empty list = clean.
        Missing snapshot is a hard failure (the file MUST exist for every
        registered pipeline — Phase 4 architecture test enforces it).
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, date, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal

# Databricks Serverless still ships Python 3.10; ``datetime.UTC`` was
# added in 3.11. Provide a 3.10-compatible alias.
UTC = UTC

if TYPE_CHECKING:
    from pyspark.sql import DataFrame


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SNAPSHOTS_DIR = REPO_ROOT / "tests" / "snapshots"

SNAPSHOT_VERSION = 1
# How many head-of-sort rows to embed in the JSON for human diffs.
SAMPLE_ROWS = 50

SnapshotSource = Literal["fixtures", "production"]


def snapshot_path(pipeline_key: str) -> Path:
    return SNAPSHOTS_DIR / f"{pipeline_key}.json"


def write_snapshot(
    df: DataFrame,
    pipeline_key: str,
    source: SnapshotSource = "fixtures",
    sort_keys: list[str] | None = None,
) -> Path:
    """Overwrite the committed snapshot.

    Args:
        df: the DataFrame to capture.
        pipeline_key: dotted path used in ``tests/snapshots/<key>.json``.
        source: where the rows came from. Stored in the snapshot for
            audit; a production-captured baseline may be re-read by
            ``capture_baseline.py`` to refresh, while a fixtures-captured
            one is regenerated by re-running fixtures.
        sort_keys: columns to sort by before hashing. If None, every
            column is used (output remains deterministic; just slower).

    Returns:
        The absolute path that was written.
    """
    target = snapshot_path(pipeline_key)
    target.parent.mkdir(parents=True, exist_ok=True)

    schema_simple = df.schema.simpleString()
    canonical = _canonical_rows(df, sort_keys=sort_keys)
    payload: dict[str, Any] = {
        "version": SNAPSHOT_VERSION,
        "pipeline_key": pipeline_key,
        "captured_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "captured_from": source,
        "row_count": len(canonical),
        "schema": schema_simple,
        "sort_keys": sort_keys or [f.name for f in df.schema.fields],
        "sample_rows": canonical[:SAMPLE_ROWS],
        "full_hash": _hash_rows(canonical),
    }
    target.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, default=_json_default) + "\n",
        encoding="utf-8",
    )
    return target


def diff_against_snapshot(df: DataFrame, pipeline_key: str) -> list[str]:
    """Compare ``df`` to the committed snapshot.

    Returns an empty list if the current output matches; otherwise a list
    of human-readable drift lines. Missing snapshot is itself a drift
    (raise via the architecture test before getting here, so callers can
    treat any non-empty list as "fail").
    """
    target = snapshot_path(pipeline_key)
    if not target.exists():
        try:
            shown = str(target.relative_to(REPO_ROOT))
        except ValueError:
            shown = str(target)
        return [
            f"snapshot file missing: {shown}. "
            f"Run `make snapshot PIPELINE={pipeline_key}` to create one."
        ]

    snap = json.loads(target.read_text(encoding="utf-8"))
    drift: list[str] = []

    schema_simple = df.schema.simpleString()
    if schema_simple != snap["schema"]:
        drift.append(
            f"Schema drift:\n  current : {schema_simple}\n  snapshot: {snap['schema']}"
        )
        return drift  # row-level diff is meaningless across mismatched schemas.

    sort_keys = snap.get("sort_keys") or None
    canonical = _canonical_rows(df, sort_keys=sort_keys)

    snap_row_count = snap["row_count"]
    current_row_count = len(canonical)
    # Baselines captured by capture_baseline.py are sample-capped (default
    # 5_000 rows, sorted by unique keys). When current output exceeds the
    # cap, apply the same prefix to make comparison meaningful — the
    # captured row_count IS the cap.
    if current_row_count > snap_row_count and snap_row_count > 0:
        canonical = canonical[:snap_row_count]

    if current_row_count != snap_row_count:
        drift.append(
            f"row count drift: current={current_row_count}, snapshot={snap_row_count}"
        )

    current_hash = _hash_rows(canonical)
    if current_hash != snap["full_hash"]:
        drift.append(
            f"content hash drift: current={current_hash[:12]}..., "
            f"snapshot={snap['full_hash'][:12]}..."
        )
        # Sample diff for context.
        snap_sample = snap["sample_rows"]
        cur_sample = canonical[:SAMPLE_ROWS]
        diff_indices = [
            i
            for i in range(min(len(snap_sample), len(cur_sample)))
            if snap_sample[i] != cur_sample[i]
        ]
        if diff_indices:
            i = diff_indices[0]
            drift.append(
                f"first-differing sample row at index {i}:\n"
                f"  current : {cur_sample[i]}\n"
                f"  snapshot: {snap_sample[i]}"
            )

    return drift


# ---------------------------------------------------------------------------
# Helpers (internal)
# ---------------------------------------------------------------------------


def _canonical_rows(df: DataFrame, sort_keys: list[str] | None) -> list[dict[str, Any]]:
    """Collect rows into a JSON-serializable list with stable ordering.

    Sort by the requested keys so two runs produce byte-identical hashes
    regardless of partition order, executor count, or scheduling. Always
    append every remaining (non-key, non-array) column as a tie-breaker
    — sort_keys may not be unique (UNIQUE_KEYS describes a logical
    primary key but the table can still have duplicate keys e.g. due to
    explode), and Spark's default tie-break order is partition-dependent.
    Array columns are skipped because Spark cannot sort by them.
    """
    columns = [f.name for f in df.schema.fields]
    primary = list(sort_keys) if sort_keys else []
    # Append every other non-array column as a deterministic tie-breaker.
    array_cols = {
        f.name
        for f in df.schema.fields
        if f.dataType.typeName() in {"array", "map", "struct"}
    }
    extras = [c for c in columns if c not in primary and c not in array_cols]
    keys = primary + extras if primary else [c for c in columns if c not in array_cols]
    sorted_df = df.orderBy(*keys) if keys else df
    rows = sorted_df.collect()
    return [_row_to_jsonable({col: row[col] for col in columns}) for row in rows]


def _row_to_jsonable(row: dict[str, Any]) -> dict[str, Any]:
    return {
        k: _json_default(v) if not _is_json_native(v) else v for k, v in row.items()
    }


def _is_json_native(v: Any) -> bool:
    return v is None or isinstance(v, str | int | float | bool | list | dict)


def _json_default(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.replace(microsecond=0).isoformat()
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, list):
        return [_json_default(v) if not _is_json_native(v) else v for v in value]
    if isinstance(value, dict):
        return {
            k: _json_default(v) if not _is_json_native(v) else v
            for k, v in value.items()
        }
    return str(value)


def _hash_rows(rows: list[dict[str, Any]]) -> str:
    payload = json.dumps(
        rows, sort_keys=True, separators=(",", ":"), default=_json_default
    )
    return "sha256:" + hashlib.sha256(payload.encode("utf-8")).hexdigest()


__all__ = [
    "SAMPLE_ROWS",
    "SNAPSHOT_VERSION",
    "SnapshotSource",
    "diff_against_snapshot",
    "snapshot_path",
    "write_snapshot",
]
