apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poorbricks-worker-orchestrator
  namespace: poorbricks-workers
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/attach"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
---
# The Airflow SA (in the 'airflow' namespace, created by Helm) needs to spawn
# worker pods in 'poorbricks-workers' namespace. The KubernetesExecutor uses this
# single SA for all orchestration.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-can-orchestrate-workers
  namespace: poorbricks-workers
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: airflow
roleRef:
  kind: Role
  name: poorbricks-worker-orchestrator
  apiGroup: rbac.authorization.k8s.io
