"""Generate Airflow DAG Python source from a parsed ``WorkflowConfig``.

The generated DAG uses ``KubernetesPodOperator`` for every task. Each
worker pod:

1. Runs an init container (``python -m poorbricks.airflow.fetch_code``)
   that downloads the table-repo tarball from the api-server's
   ``/v1/code/{prefix}`` endpoint into an ``emptyDir`` at ``/workspace`` —
   so workers need no shared PVC and can run on any node.
2. Pulls ``MONGO_URI`` / ``POSTGRES_*`` from a ``Secret`` referenced via
   ``env_from``.
3. Executes ``poorbricks run --pipeline <key> --mode production`` or
   ``poorbricks check --pipeline <key>`` (see ``TaskConfig.command``).
4. Prefers a Spot VM (soft node-affinity on ``cloud.google.com/gke-spot``
   plus a toleration for the ``spot`` taint), falling back to on-demand.
"""

from __future__ import annotations

import re
import textwrap
from datetime import datetime

from poorbricks.constants import (
    DEFAULT_CODE_API_URL,
    DEFAULT_NAMESPACE,
    DEFAULT_POSTGRES_CREDS_SECRET_NAME,
    DEFAULT_RUNTIME_SECRET_NAME,
)

from .workflow import TaskConfig, WorkflowConfig

_PREFIX_RE = re.compile(r"^[A-Za-z0-9_-]+$")

# Worker pod CPU / memory — requests equal limits. Worker pods now schedule on
# their own (Spot) nodes rather than the cramped DAG node, so reserving the
# real figure is both safe and necessary: it stops Kubernetes overcommitting a
# node with more bursting pods than it can run. ``SPARK_MASTER`` is pinned to
# ``local[_WORKER_CPU]`` so Spark starts exactly this many task threads.
_WORKER_CPU = 2
_WORKER_MEMORY = "4Gi"


def generate_dag_file(
    workflow: WorkflowConfig,
    *,
    prefix: str,
    image: str,
    namespace: str = DEFAULT_NAMESPACE,
    runtime_secret: str = DEFAULT_RUNTIME_SECRET_NAME,
    postgres_creds_secret: str = DEFAULT_POSTGRES_CREDS_SECRET_NAME,
    code_api_url: str = DEFAULT_CODE_API_URL,
    start_year: int | None = None,
) -> str:
    """Render Python source for an Airflow DAG.

    Args:
        workflow: parsed workflow YAML.
        prefix: namespacing prefix (typically the table-repo name); selects
            the api-server ``/v1/code/{prefix}`` tarball the init container
            downloads.
        image: full image reference for the worker container — must have the
            framework installed; table code is fetched at pod startup.
        namespace: K8s namespace the worker pods run in.
        runtime_secret: K8s ``Secret`` exposed via ``env_from`` (e.g.
            ``MONGO_URI``).
        postgres_creds_secret: K8s ``Secret`` holding VSO-managed postgres
            credentials; keys ``username`` / ``password`` are mapped to
            ``POSTGRES_USER`` / ``POSTGRES_PASSWORD`` in every worker pod.
        code_api_url: base URL of the api-server the init container fetches
            table code from.
        start_year: ``DAG.start_date`` year override (test hook).
    """
    _validate_prefix(prefix)
    dag_id = f"{prefix}__{workflow.name}"
    year = start_year if start_year is not None else datetime.utcnow().year

    parts: list[str] = [
        _render_header(),
        _render_constants(
            dag_id=dag_id,
            prefix=prefix,
            namespace=namespace,
            schedule=workflow.schedule,
            year=year,
            image=image,
            runtime_secret=runtime_secret,
            postgres_creds_secret=postgres_creds_secret,
            code_api_url=code_api_url,
        ),
        _render_dag(),
        _render_volumes_and_env(),
        _render_build_task(),
        _render_tasks(workflow.tasks),
        _render_dependencies(workflow.tasks),
    ]
    return "\n\n".join(p.strip() for p in parts) + "\n"


def _validate_prefix(prefix: str) -> None:
    if not prefix or not _PREFIX_RE.fullmatch(prefix):
        raise ValueError(f"prefix must match [A-Za-z0-9_-]+, got {prefix!r}")


def _render_header() -> str:
    return textwrap.dedent(
        '''\
        """Auto-generated by poorbricks.airflow.dag_generator. Do not edit."""

        from __future__ import annotations

        from datetime import datetime, timedelta

        from airflow import DAG
        from airflow.providers.cncf.kubernetes.operators.pod import (
            KubernetesPodOperator,
        )
        from kubernetes.client import models as k8s
        '''
    )


def _render_constants(
    *,
    dag_id: str,
    prefix: str,
    namespace: str,
    schedule: str | None,
    year: int,
    image: str,
    runtime_secret: str,
    postgres_creds_secret: str,
    code_api_url: str,
) -> str:
    return (
        f"DAG_ID = {dag_id!r}\n"
        f"PREFIX = {prefix!r}\n"
        f"NAMESPACE = {namespace!r}\n"
        f"SCHEDULE = {schedule!r}  # None = manual trigger only\n"
        f"START_DATE = datetime({year}, 1, 1)\n"
        f"IMAGE = {image!r}\n"
        f"RUNTIME_SECRET = {runtime_secret!r}\n"
        f"POSTGRES_CREDS_SECRET = {postgres_creds_secret!r}\n"
        f"CODE_TARBALL_URL = {f'{code_api_url}/v1/code/{prefix}'!r}\n"
    )


def _render_dag() -> str:
    return textwrap.dedent(
        """\
        dag = DAG(
            dag_id=DAG_ID,
            schedule=SCHEDULE,
            start_date=START_DATE,
            catchup=False,
            max_active_runs=1,
            # Retry tasks killed by transient node pressure so a single
            # failure does not fail the whole run; pipelines write
            # idempotently to Postgres.
            default_args={"retries": 2, "retry_delay": timedelta(minutes=2)},
            tags=[PREFIX, "poorbricks"],
            is_paused_upon_creation=False,
        )
        """
    )


def _render_volumes_and_env() -> str:
    rendered = textwrap.dedent(
        """\
        # Table code is fetched at startup by the fetch-code init container
        # into this emptyDir — no shared PVC, so the pod runs on any node.
        _CODE_VOLUME = k8s.V1Volume(
            name="code",
            empty_dir=k8s.V1EmptyDirVolumeSource(),
        )

        _CODE_MOUNT = k8s.V1VolumeMount(
            name="code",
            mount_path="/workspace",
        )

        # Scratch disk for Spark shuffle / sort / spill — lets pipelines
        # process datasets larger than the pod's RAM.
        _SCRATCH_VOLUME = k8s.V1Volume(
            name="spark-tmp",
            empty_dir=k8s.V1EmptyDirVolumeSource(size_limit="20Gi"),
        )

        _SCRATCH_MOUNT = k8s.V1VolumeMount(
            name="spark-tmp",
            mount_path="/spark-tmp",
        )

        _VOLUMES = [_CODE_VOLUME, _SCRATCH_VOLUME]

        # Init container: download the table-repo tarball from the api-server
        # into /workspace before the worker starts. Reuses the worker image
        # (already IfNotPresent-cached) so there is no extra image pull.
        _INIT_CONTAINERS = [
            k8s.V1Container(
                name="fetch-code",
                image=IMAGE,
                command=["python", "-m", "poorbricks.airflow.fetch_code"],
                env=[
                    k8s.V1EnvVar(name="CODE_TARBALL_URL", value=CODE_TARBALL_URL),
                ],
                volume_mounts=[_CODE_MOUNT],
            )
        ]

        # Prefer a Spot VM (soft — falls back to on-demand) and tolerate the
        # Spot taint so the pod is allowed onto the spot node pool.
        _AFFINITY = k8s.V1Affinity(
            node_affinity=k8s.V1NodeAffinity(
                preferred_during_scheduling_ignored_during_execution=[
                    k8s.V1PreferredSchedulingTerm(
                        weight=100,
                        preference=k8s.V1NodeSelectorTerm(
                            match_expressions=[
                                k8s.V1NodeSelectorRequirement(
                                    key="cloud.google.com/gke-spot",
                                    operator="In",
                                    values=["true"],
                                )
                            ]
                        ),
                    )
                ]
            )
        )

        _TOLERATIONS = [
            k8s.V1Toleration(
                key="spot",
                operator="Equal",
                value="true",
                effect="NoSchedule",
            )
        ]

        _ENV_FROM = [
            k8s.V1EnvFromSource(
                secret_ref=k8s.V1SecretEnvSource(name=RUNTIME_SECRET),
            ),
            k8s.V1EnvFromSource(
                secret_ref=k8s.V1SecretEnvSource(name=POSTGRES_CREDS_SECRET),
            ),
        ]

        # Requests equal limits for CPU / memory: worker pods run on their own
        # (Spot) nodes, so Kubernetes schedules only as many as a node can
        # truly run — each gets its full CPU / memory with no throttling.
        _WORKER_RESOURCES = k8s.V1ResourceRequirements(
            requests={
                "cpu": "__WORKER_CPU__",
                "memory": "__WORKER_MEMORY__",
                "ephemeral-storage": "1Gi",
            },
            limits={
                "cpu": "__WORKER_CPU__",
                "memory": "__WORKER_MEMORY__",
                "ephemeral-storage": "20Gi",
            },
        )

        _ENV_VARS = [
            k8s.V1EnvVar(name="TABLES_ROOT", value="/workspace/tables"),
            k8s.V1EnvVar(name="PYTHONPATH", value="/workspace:/app"),
            k8s.V1EnvVar(name="PYTHONUNBUFFERED", value="1"),
            k8s.V1EnvVar(name="SPARK_LOCAL_DIR", value="/spark-tmp"),
            # Pin Spark to the pod's CPU limit so it starts exactly that many
            # local task threads instead of guessing from cgroups.
            k8s.V1EnvVar(name="SPARK_MASTER", value="local[__WORKER_CPU__]"),
            k8s.V1EnvVar(
                name="POSTGRES_USER",
                value_from=k8s.V1EnvVarSource(
                    secret_key_ref=k8s.V1SecretKeySelector(
                        name=POSTGRES_CREDS_SECRET,
                        key="username",
                    )
                ),
            ),
            k8s.V1EnvVar(
                name="POSTGRES_PASSWORD",
                value_from=k8s.V1EnvVarSource(
                    secret_key_ref=k8s.V1SecretKeySelector(
                        name=POSTGRES_CREDS_SECRET,
                        key="password",
                    )
                ),
            ),
            k8s.V1EnvVar(name="POSTGRES_HOST", value="postgresql-rw.storage.svc.cluster.local"),
            k8s.V1EnvVar(name="POSTGRES_PORT", value="5432"),
            k8s.V1EnvVar(name="POSTGRES_DB", value="poorbricks"),
            # In-cluster workers have no Tailscale; ContractSource must reach
            # the poorbricks server over the cluster Service, not *.ts.net.
            k8s.V1EnvVar(
                name="CONTRACTS_API_URL",
                value="http://poorbricks-server.airflow.svc.cluster.local:8080",
            ),
        ]
        """
    )
    return rendered.replace("__WORKER_CPU__", str(_WORKER_CPU)).replace(
        "__WORKER_MEMORY__", _WORKER_MEMORY
    )


def _render_build_task() -> str:
    return textwrap.dedent(
        """\
        _COMMAND_ARGS = {
            "run": ["run", "--mode", "production"],
            "check": ["check"],
        }


        def _build_task(
            task_id: str, pipeline_key: str, command: str
        ) -> KubernetesPodOperator:
            base_args = _COMMAND_ARGS[command]
            arguments = [base_args[0], "--pipeline", pipeline_key, *base_args[1:]]
            return KubernetesPodOperator(
                task_id=task_id,
                name=f"{DAG_ID}-{task_id}",
                namespace=NAMESPACE,
                image=IMAGE,
                cmds=["poorbricks"],
                arguments=arguments,
                volumes=_VOLUMES,
                volume_mounts=[_CODE_MOUNT, _SCRATCH_MOUNT],
                init_containers=_INIT_CONTAINERS,
                env_from=_ENV_FROM,
                env_vars=_ENV_VARS,
                container_resources=_WORKER_RESOURCES,
                affinity=_AFFINITY,
                tolerations=_TOLERATIONS,
                get_logs=True,
                in_cluster=True,
                on_finish_action="delete_pod",
                reattach_on_restart=False,
                do_xcom_push=False,
                # The image tag is an immutable git SHA, so skip the re-pull of
                # the multi-GB image on every task — pods start far faster.
                image_pull_policy="IfNotPresent",
                # A pod may sit Pending while the cluster autoscaler adds a
                # node or siblings finish; wait for a slot, don't fail.
                startup_timeout_seconds=900,
                dag=dag,
            )
        """
    )


def _render_tasks(tasks: tuple[TaskConfig, ...]) -> str:
    return "\n".join(
        f"{_task_var(t.id)} = _build_task({t.id!r}, {t.pipeline!r}, {t.command!r})"
        for t in tasks
    )


def _render_dependencies(tasks: tuple[TaskConfig, ...]) -> str:
    edges = [
        f"{_task_var(dep)} >> {_task_var(task.id)}"
        for task in tasks
        for dep in task.depends_on
    ]
    return "\n".join(edges) if edges else "# (no inter-task dependencies)"


def _task_var(task_id: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", task_id)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return f"task_{cleaned}"


__all__ = ["generate_dag_file"]
