"""Generate Airflow DAG Python source from a parsed ``WorkflowConfig``.

The generated DAG uses ``KubernetesPodOperator`` for every task. Each
worker pod:

1. Runs an init container that ``git clone --depth 1`` the table-repo
   into an ``emptyDir`` shared with the main container, then checks out
   the pinned SHA.
2. Starts the main container at ``/workspace`` with ``TABLES_ROOT`` set
   so ``poorbricks.discovery`` finds the repo's pipelines.
3. Pulls ``MONGO_URI`` / ``POSTGRES_*`` from a ``Secret`` referenced via
   ``env_from``.
4. Executes ``poorbricks run --pipeline <key> --mode production``.
"""

from __future__ import annotations

import re
import textwrap
from datetime import datetime

from poorbricks.constants import DEFAULT_NAMESPACE, DEFAULT_RUNTIME_SECRET_NAME

from .workflow import TaskConfig, WorkflowConfig

_PREFIX_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def generate_dag_file(
    workflow: WorkflowConfig,
    *,
    prefix: str,
    image: str,
    table_repo_url: str,
    table_repo_sha: str,
    namespace: str = DEFAULT_NAMESPACE,
    runtime_secret: str = DEFAULT_RUNTIME_SECRET_NAME,
    repo_clone_secret: str | None = None,
    start_year: int | None = None,
) -> str:
    """Render Python source for an Airflow DAG.

    Args:
        workflow: parsed workflow YAML.
        prefix: namespacing prefix (typically the table-repo name).
        image: full image reference for the worker container.
        table_repo_url: git URL the init container will clone.
        table_repo_sha: commit SHA the init container will check out.
        namespace: K8s namespace the worker pods run in.
        runtime_secret: K8s ``Secret`` exposed via ``env_from`` (e.g.
            ``MONGO_URI``, ``POSTGRES_*``).
        repo_clone_secret: optional K8s ``Secret`` with an SSH key for
            cloning private repos; mounted into the init container at
            ``/root/.ssh``.
        start_year: ``DAG.start_date`` year override (test hook).
    """
    _validate_prefix(prefix)
    dag_id = f"{prefix}__{workflow.name}"
    year = start_year if start_year is not None else datetime.utcnow().year

    parts: list[str] = [
        _render_header(),
        _render_constants(
            dag_id=dag_id,
            prefix=prefix,
            namespace=namespace,
            schedule=workflow.schedule,
            year=year,
            image=image,
            table_repo_url=table_repo_url,
            table_repo_sha=table_repo_sha,
            runtime_secret=runtime_secret,
        ),
        _render_dag(),
        _render_init_container(repo_clone_secret),
        _render_volumes_and_env(repo_clone_secret),
        _render_build_task(),
        _render_tasks(workflow.tasks),
        _render_dependencies(workflow.tasks),
    ]
    return "\n\n".join(p.strip() for p in parts) + "\n"


def _validate_prefix(prefix: str) -> None:
    if not prefix or not _PREFIX_RE.fullmatch(prefix):
        raise ValueError(f"prefix must match [A-Za-z0-9_-]+, got {prefix!r}")


def _render_header() -> str:
    return textwrap.dedent(
        '''\
        """Auto-generated by poorbricks.airflow.dag_generator. Do not edit."""

        from __future__ import annotations

        from datetime import datetime

        from airflow import DAG
        from airflow.providers.cncf.kubernetes.operators.pod import (
            KubernetesPodOperator,
        )
        from kubernetes.client import models as k8s
        '''
    )


def _render_constants(
    *,
    dag_id: str,
    prefix: str,
    namespace: str,
    schedule: str,
    year: int,
    image: str,
    table_repo_url: str,
    table_repo_sha: str,
    runtime_secret: str,
) -> str:
    return (
        f"DAG_ID = {dag_id!r}\n"
        f"PREFIX = {prefix!r}\n"
        f"NAMESPACE = {namespace!r}\n"
        f"SCHEDULE = {schedule!r}\n"
        f"START_DATE = datetime({year}, 1, 1)\n"
        f"IMAGE = {image!r}\n"
        f"TABLE_REPO_URL = {table_repo_url!r}\n"
        f"TABLE_REPO_SHA = {table_repo_sha!r}\n"
        f"RUNTIME_SECRET = {runtime_secret!r}\n"
    )


def _render_dag() -> str:
    return textwrap.dedent(
        """\
        dag = DAG(
            dag_id=DAG_ID,
            schedule=SCHEDULE,
            start_date=START_DATE,
            catchup=False,
            max_active_runs=1,
            tags=[PREFIX, "poorbricks"],
            is_paused_upon_creation=False,
        )
        """
    )


def _render_init_container(repo_clone_secret: str | None) -> str:
    ssh_mount = ""
    if repo_clone_secret:
        ssh_mount = textwrap.indent(
            textwrap.dedent(
                """\
                k8s.V1VolumeMount(
                    name="repo-clone-key",
                    mount_path="/root/.ssh",
                    read_only=True,
                ),
                """
            ),
            "        ",
        )
    return textwrap.dedent(
        """\
        _CODE_VOLUME = k8s.V1Volume(
            name="code",
            empty_dir=k8s.V1EmptyDirVolumeSource(),
        )

        _CODE_MOUNT = k8s.V1VolumeMount(
            name="code",
            mount_path="/workspace",
        )

        _INIT_CONTAINER = k8s.V1Container(
            name="fetch-code",
            image="alpine/git:2.43.0",
            command=["sh", "-c"],
            args=[
                "set -e && "
                "git clone " + TABLE_REPO_URL + " /workspace && "
                "cd /workspace && "
                "git checkout " + TABLE_REPO_SHA
            ],
            volume_mounts=[
                k8s.V1VolumeMount(name="code", mount_path="/workspace"),
        __SSH_MOUNT__    ],
        )
        """
    ).replace("__SSH_MOUNT__", ssh_mount)


def _render_volumes_and_env(repo_clone_secret: str | None) -> str:
    if repo_clone_secret:
        volumes = (
            "_VOLUMES = [\n"
            "    _CODE_VOLUME,\n"
            "    k8s.V1Volume(\n"
            '        name="repo-clone-key",\n'
            "        secret=k8s.V1SecretVolumeSource(\n"
            f"            secret_name={repo_clone_secret!r},\n"
            "            default_mode=0o400,\n"
            "        ),\n"
            "    ),\n"
            "]\n"
        )
    else:
        volumes = "_VOLUMES = [_CODE_VOLUME]\n"
    env_block = textwrap.dedent(
        """\
        _ENV_FROM = [
            k8s.V1EnvFromSource(
                secret_ref=k8s.V1SecretEnvSource(name=RUNTIME_SECRET),
            ),
        ]

        _ENV_VARS = [
            k8s.V1EnvVar(name="TABLES_ROOT", value="/workspace/tables"),
            k8s.V1EnvVar(name="PYTHONUNBUFFERED", value="1"),
        ]
        """
    )
    return volumes + "\n" + env_block


def _render_build_task() -> str:
    return textwrap.dedent(
        """\
        def _build_task(task_id: str, pipeline_key: str) -> KubernetesPodOperator:
            return KubernetesPodOperator(
                task_id=task_id,
                name=f"{DAG_ID}-{task_id}",
                namespace=NAMESPACE,
                image=IMAGE,
                cmds=["poorbricks"],
                arguments=["run", "--pipeline", pipeline_key, "--mode", "production"],
                init_containers=[_INIT_CONTAINER],
                volumes=_VOLUMES,
                volume_mounts=[_CODE_MOUNT],
                env_from=_ENV_FROM,
                env_vars=_ENV_VARS,
                get_logs=True,
                in_cluster=True,
                is_delete_operator_pod=True,
                image_pull_policy="IfNotPresent",
                dag=dag,
            )
        """
    )


def _render_tasks(tasks: tuple[TaskConfig, ...]) -> str:
    return "\n".join(
        f"{_task_var(t.id)} = _build_task({t.id!r}, {t.pipeline!r})" for t in tasks
    )


def _render_dependencies(tasks: tuple[TaskConfig, ...]) -> str:
    edges = [
        f"{_task_var(dep)} >> {_task_var(task.id)}"
        for task in tasks
        for dep in task.depends_on
    ]
    return "\n".join(edges) if edges else "# (no inter-task dependencies)"


def _task_var(task_id: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", task_id)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return f"task_{cleaned}"


__all__ = ["generate_dag_file"]
