"""Generate Airflow DAG Python source from a parsed ``WorkflowConfig``.

The generated DAG uses ``KubernetesPodOperator`` for every task. Each
worker pod:

1. Mounts the shared ``airflow-dags`` PVC at ``/workspace`` with subPath
   ``__code__/{prefix}/`` — the api-server extracts each uploaded tarball
   there at upload time, so the worker sees ``/workspace/tables`` and the
   framework finds pipelines via ``TABLES_ROOT``.
2. Pulls ``MONGO_URI`` / ``POSTGRES_*`` from a ``Secret`` referenced via
   ``env_from``.
3. Executes ``poorbricks run --pipeline <key> --mode production`` or
   ``poorbricks check --pipeline <key>`` (see ``TaskConfig.command``).
4. Lands on the node labeled ``poorbricks.io/dags=true`` so the RWO PVC
   can attach — same node as the scheduler / dag-processor / api-server.
"""

from __future__ import annotations

import re
import textwrap
from datetime import datetime

from poorbricks.constants import (
    DEFAULT_NAMESPACE,
    DEFAULT_POSTGRES_CREDS_SECRET_NAME,
    DEFAULT_RUNTIME_SECRET_NAME,
)

from .workflow import TaskConfig, WorkflowConfig

_PREFIX_RE = re.compile(r"^[A-Za-z0-9_-]+$")

DEFAULT_CODE_PVC_CLAIM = "airflow-dags"
DEFAULT_CODE_PVC_ROOT = "__code__"
DEFAULT_NODE_SELECTOR_KEY = "poorbricks.io/dags"
DEFAULT_NODE_SELECTOR_VALUE = "true"

# Worker pod CPU — single source of truth shared by the K8s resource block and
# the Spark master string. The resource request equals the limit (see
# ``_render_volumes_and_env``) so the node is never oversubscribed, and
# ``SPARK_MASTER`` is pinned to ``local[_WORKER_CPU]`` so Spark starts exactly
# this many task threads instead of guessing from cgroups.
_WORKER_CPU = 2


def generate_dag_file(
    workflow: WorkflowConfig,
    *,
    prefix: str,
    image: str,
    namespace: str = DEFAULT_NAMESPACE,
    runtime_secret: str = DEFAULT_RUNTIME_SECRET_NAME,
    postgres_creds_secret: str = DEFAULT_POSTGRES_CREDS_SECRET_NAME,
    code_pvc_claim: str = DEFAULT_CODE_PVC_CLAIM,
    code_pvc_root: str = DEFAULT_CODE_PVC_ROOT,
    node_selector: dict[str, str] | None = None,
    start_year: int | None = None,
) -> str:
    """Render Python source for an Airflow DAG.

    Args:
        workflow: parsed workflow YAML.
        prefix: namespacing prefix (typically the table-repo name); becomes
            the subPath under ``code_pvc_root`` on the PVC.
        image: full image reference for the worker container — must have
            the framework installed; tables come from the PVC mount.
        namespace: K8s namespace the worker pods run in.
        runtime_secret: K8s ``Secret`` exposed via ``env_from`` (e.g.
            ``MONGO_URI``).
        postgres_creds_secret: K8s ``Secret`` holding VSO-managed postgres
            credentials; keys ``username`` / ``password`` are mapped to
            ``POSTGRES_USER`` / ``POSTGRES_PASSWORD`` in every worker pod.
        code_pvc_claim: PVC name the api-server wrote extracted tables to.
        code_pvc_root: directory inside the PVC under which the
            api-server keeps each ``{prefix}/tables`` tree.
        node_selector: required ``nodeSelector`` so workers land on the
            same node as the RWO PVC. Defaults to ``poorbricks.io/dags=true``.
        start_year: ``DAG.start_date`` year override (test hook).
    """
    _validate_prefix(prefix)
    dag_id = f"{prefix}__{workflow.name}"
    year = start_year if start_year is not None else datetime.utcnow().year
    selector = node_selector or {DEFAULT_NODE_SELECTOR_KEY: DEFAULT_NODE_SELECTOR_VALUE}

    parts: list[str] = [
        _render_header(),
        _render_constants(
            dag_id=dag_id,
            prefix=prefix,
            namespace=namespace,
            schedule=workflow.schedule,
            year=year,
            image=image,
            runtime_secret=runtime_secret,
            postgres_creds_secret=postgres_creds_secret,
            code_pvc_claim=code_pvc_claim,
            code_pvc_root=code_pvc_root,
            node_selector=selector,
        ),
        _render_dag(),
        _render_volumes_and_env(),
        _render_build_task(),
        _render_tasks(workflow.tasks),
        _render_dependencies(workflow.tasks),
    ]
    return "\n\n".join(p.strip() for p in parts) + "\n"


def _validate_prefix(prefix: str) -> None:
    if not prefix or not _PREFIX_RE.fullmatch(prefix):
        raise ValueError(f"prefix must match [A-Za-z0-9_-]+, got {prefix!r}")


def _render_header() -> str:
    return textwrap.dedent(
        '''\
        """Auto-generated by poorbricks.airflow.dag_generator. Do not edit."""

        from __future__ import annotations

        from datetime import datetime, timedelta

        from airflow import DAG
        from airflow.providers.cncf.kubernetes.operators.pod import (
            KubernetesPodOperator,
        )
        from kubernetes.client import models as k8s
        '''
    )


def _render_constants(
    *,
    dag_id: str,
    prefix: str,
    namespace: str,
    schedule: str | None,
    year: int,
    image: str,
    runtime_secret: str,
    postgres_creds_secret: str,
    code_pvc_claim: str,
    code_pvc_root: str,
    node_selector: dict[str, str],
) -> str:
    return (
        f"DAG_ID = {dag_id!r}\n"
        f"PREFIX = {prefix!r}\n"
        f"NAMESPACE = {namespace!r}\n"
        f"SCHEDULE = {schedule!r}  # None = manual trigger only\n"
        f"START_DATE = datetime({year}, 1, 1)\n"
        f"IMAGE = {image!r}\n"
        f"RUNTIME_SECRET = {runtime_secret!r}\n"
        f"POSTGRES_CREDS_SECRET = {postgres_creds_secret!r}\n"
        f"CODE_PVC_CLAIM = {code_pvc_claim!r}\n"
        f"CODE_SUBPATH = {f'{code_pvc_root}/{prefix}'!r}\n"
        f"NODE_SELECTOR = {dict(node_selector)!r}\n"
    )


def _render_dag() -> str:
    return textwrap.dedent(
        """\
        dag = DAG(
            dag_id=DAG_ID,
            schedule=SCHEDULE,
            start_date=START_DATE,
            catchup=False,
            max_active_runs=1,
            # Retry tasks killed by transient node pressure so a single
            # failure does not fail the whole run; pipelines write
            # idempotently to Postgres.
            default_args={"retries": 2, "retry_delay": timedelta(minutes=2)},
            tags=[PREFIX, "poorbricks"],
            is_paused_upon_creation=False,
        )
        """
    )


def _render_volumes_and_env() -> str:
    rendered = textwrap.dedent(
        """\
        _CODE_VOLUME = k8s.V1Volume(
            name="code",
            persistent_volume_claim=k8s.V1PersistentVolumeClaimVolumeSource(
                claim_name=CODE_PVC_CLAIM,
                read_only=True,
            ),
        )

        _CODE_MOUNT = k8s.V1VolumeMount(
            name="code",
            mount_path="/workspace",
            sub_path=CODE_SUBPATH,
            read_only=True,
        )

        # Scratch disk for Spark shuffle / sort / spill — lets pipelines
        # process datasets larger than the pod's RAM.
        _SCRATCH_VOLUME = k8s.V1Volume(
            name="spark-tmp",
            empty_dir=k8s.V1EmptyDirVolumeSource(size_limit="20Gi"),
        )

        _SCRATCH_MOUNT = k8s.V1VolumeMount(
            name="spark-tmp",
            mount_path="/spark-tmp",
        )

        _VOLUMES = [_CODE_VOLUME, _SCRATCH_VOLUME]

        _ENV_FROM = [
            k8s.V1EnvFromSource(
                secret_ref=k8s.V1SecretEnvSource(name=RUNTIME_SECRET),
            ),
            k8s.V1EnvFromSource(
                secret_ref=k8s.V1SecretEnvSource(name=POSTGRES_CREDS_SECRET),
            ),
        ]

        # Requests equal limits for CPU / memory so Kubernetes schedules only
        # as many workers as the node can truly run: each running pod then gets
        # its full CPU / memory with no throttling, instead of many pods
        # thrashing one oversubscribed node.
        _WORKER_RESOURCES = k8s.V1ResourceRequirements(
            requests={
                "cpu": "__WORKER_CPU__",
                "memory": "4Gi",
                "ephemeral-storage": "1Gi",
            },
            limits={
                "cpu": "__WORKER_CPU__",
                "memory": "4Gi",
                "ephemeral-storage": "20Gi",
            },
        )

        _ENV_VARS = [
            k8s.V1EnvVar(name="TABLES_ROOT", value="/workspace/tables"),
            k8s.V1EnvVar(name="PYTHONPATH", value="/workspace:/app"),
            k8s.V1EnvVar(name="PYTHONUNBUFFERED", value="1"),
            k8s.V1EnvVar(name="SPARK_LOCAL_DIR", value="/spark-tmp"),
            # Pin Spark to the pod's CPU limit so it starts exactly that many
            # local task threads instead of guessing from cgroups.
            k8s.V1EnvVar(name="SPARK_MASTER", value="local[__WORKER_CPU__]"),
            k8s.V1EnvVar(
                name="POSTGRES_USER",
                value_from=k8s.V1EnvVarSource(
                    secret_key_ref=k8s.V1SecretKeySelector(
                        name=POSTGRES_CREDS_SECRET,
                        key="username",
                    )
                ),
            ),
            k8s.V1EnvVar(
                name="POSTGRES_PASSWORD",
                value_from=k8s.V1EnvVarSource(
                    secret_key_ref=k8s.V1SecretKeySelector(
                        name=POSTGRES_CREDS_SECRET,
                        key="password",
                    )
                ),
            ),
            k8s.V1EnvVar(name="POSTGRES_HOST", value="postgresql-rw.storage.svc.cluster.local"),
            k8s.V1EnvVar(name="POSTGRES_PORT", value="5432"),
            k8s.V1EnvVar(name="POSTGRES_DB", value="poorbricks"),
            # In-cluster workers have no Tailscale; ContractSource must reach
            # the poorbricks server over the cluster Service, not *.ts.net.
            k8s.V1EnvVar(
                name="CONTRACTS_API_URL",
                value="http://poorbricks-server.airflow.svc.cluster.local:8080",
            ),
        ]
        """
    )
    return rendered.replace("__WORKER_CPU__", str(_WORKER_CPU))


def _render_build_task() -> str:
    return textwrap.dedent(
        """\
        _COMMAND_ARGS = {
            "run": ["run", "--mode", "production"],
            "check": ["check"],
        }


        def _build_task(
            task_id: str, pipeline_key: str, command: str
        ) -> KubernetesPodOperator:
            base_args = _COMMAND_ARGS[command]
            arguments = [base_args[0], "--pipeline", pipeline_key, *base_args[1:]]
            return KubernetesPodOperator(
                task_id=task_id,
                name=f"{DAG_ID}-{task_id}",
                namespace=NAMESPACE,
                image=IMAGE,
                cmds=["poorbricks"],
                arguments=arguments,
                volumes=_VOLUMES,
                volume_mounts=[_CODE_MOUNT, _SCRATCH_MOUNT],
                env_from=_ENV_FROM,
                env_vars=_ENV_VARS,
                container_resources=_WORKER_RESOURCES,
                node_selector=NODE_SELECTOR,
                get_logs=True,
                in_cluster=True,
                on_finish_action="delete_pod",
                reattach_on_restart=False,
                do_xcom_push=False,
                # The image tag is an immutable git SHA, so skip the re-pull of
                # the multi-GB image on every task — pods start far faster.
                image_pull_policy="IfNotPresent",
                # All worker pods are pinned (RWO PVC) to one shared node, so a
                # pod may sit Pending while siblings finish; wait, don't fail.
                startup_timeout_seconds=900,
                dag=dag,
            )
        """
    )


def _render_tasks(tasks: tuple[TaskConfig, ...]) -> str:
    return "\n".join(
        f"{_task_var(t.id)} = _build_task({t.id!r}, {t.pipeline!r}, {t.command!r})"
        for t in tasks
    )


def _render_dependencies(tasks: tuple[TaskConfig, ...]) -> str:
    edges = [
        f"{_task_var(dep)} >> {_task_var(task.id)}"
        for task in tasks
        for dep in task.depends_on
    ]
    return "\n".join(edges) if edges else "# (no inter-task dependencies)"


def _task_var(task_id: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", task_id)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return f"task_{cleaned}"


__all__ = ["generate_dag_file"]
