apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
type: Opaque
stringData:
  fernet-key: "GVRU8dlXJNlcEtuFu5IqBShQRxTxtHfgJ_s2ZFo8QcM="
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgresql
  namespace: airflow
type: Opaque
stringData:
  connection: "postgresql://airflow:airflow@airflow-postgresql:5432/airflow"
  password: "airflow"
